apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: airflow-web-ingress
  namespace: airflow
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
    - host: 172-30-1-240.nip.io   # ← nip.io 이용
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: airflow-webserver
                port:
                  number: 8080