executor: "KubernetesExecutor"

config:
  core:
    dags_folder: "/opt/airflow/dags/repo/dags"
    executor: "KubernetesExecutor"
    dags_are_paused_at_creation: "True"
    load_examples: "False"
  api:
    auth_backend: "airflow.api.auth.backend.basic_auth"
  logging:
    remote_logging: "False"
    logging_level: "INFO"
  kubernetes:
    delete_worker_pods: "False"
    delete_worker_pods_on_failure: "False"
    delete_worker_pods_on_success: "False"
  smtp:
    smtp_host: smtp.gmail.com
    smtp_port: "587"         # STARTTLS용
    smtp_starttls: "True"
    smtp_ssl: "False"
    smtp_mail_from: "seungyeup126.smtp@gmail.com"

images:
  airflow:
    repository: "dave126/airflow-custom"
    tag: "2.9.3-amd64"
    pullPolicy: "Always"

airflow:
  extraEnvFrom:
    - secretRef:
        name: airflow-env-vars

  extraEnv:
    # Postgres 커넥션
    - name: AIRFLOW_CONN_POSTGRES_DEFAULT
      valueFrom:
        secretKeyRef:
          name: airflow-postgresql
          key: postgres-password

    # SMTP 기본 커넥션을 환경변수로 정의
    # - name: AIRFLOW_CONN_SMTP_DEFAULT
    #   valueFrom:
    #     secretKeyRef:
    #       name: airflow-env-vars
    #       key: SMTP_CONN
    # DAG에서 참조하는 이메일 환경변수만 로드
    # - name: YOUTH_HOUSING_SENDER_EMAIL
    #   valueFrom:
    #     secretKeyRef:
    #       name: airflow-env-vars
    #       key: YOUTH_HOUSING_SENDER_EMAIL
    # - name: YOUTH_HOUSING_SENDER_PASSWORD
    #   valueFrom:
    #     secretKeyRef:
    #       name: airflow-env-vars
    #       key: YOUTH_HOUSING_SENDER_PASSWORD
    # - name: YOUTH_HOUSING_RECEIVER_EMAILS
    #   valueFrom:
    #     secretKeyRef:
    #       name: airflow-env-vars
    #       key: YOUTH_HOUSING_RECEIVER_EMAILS

dags:
  gitSync:
    enabled: true
    repo: "https://github.com/Seungyeup/ScrapeAndAlert.git"
    ref: "main"
    branch: "main"
    subPath: "dags"
    wait: 60

webserver:
  service:
    type: "NodePort"
    ports:
      - name: "airflow-ui"
        port: 8080
        targetPort: "airflow-ui"
        nodePort: 30097

postgresql:
  primary:
    persistence:
      enabled: true
      storageClass: "local-path"